apiVersion: apps/v1
kind: Deployment
metadata:
  name: wine-quality-mlflow-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-serving
  template:
    metadata:
      labels:
        app: mlflow-serving
    spec:
      containers:
      - name: mlflow-serving
        image: your_dockerhub/wine-quality-mlflow-serving:latest
        ports:
        - containerPort: 5000
        env:
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow-tracking.cloud:5001
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow-serving
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
