services:
  mlflow-init:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    volumes:
      - mlflow_data:/mlflow
    user: root
    command: >
      sh -c "
        mkdir -p /mlflow/artifacts &&
        chmod -R 777 /mlflow &&
        chown -R 1000:1000 /mlflow
      "

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    depends_on:
      mlflow-init:
        condition: service_completed_successfully
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mlflow_data:
    driver: local
