data:
  raw_data_red:   "data/raw/winequality-red.csv"
  raw_data_white: "data/raw/winequality-white.csv"

problem:
  type: "regression"            # switch to "classification" or "binary_classification" if desired

mlflow:
  experiment_name:  "wine-quality-exp"
  tracking_uri:     "http://127.0.0.1:5000"

  server:
    host:           "0.0.0.0"   # bind to all interfaces inside Codespaces
    port:           5000
    backend_store_uri:  "sqlite:///mlflow.db"
    artifact_root:      "./mlartifacts"
    workers: 1

logging:
  level:  "INFO"
